import {
  Profile,
  Panorama,
  Stage,
  Hotspot,
  Question,
  QuestionOption,
  SiteContent,
  ActivityLog,
} from '../types/database';
import { PUBLIC_PANORAMAS, BUNDLED_PANORAMAS } from '../assets/panoramas';

export const initialProfiles: Profile[] = [
  {
    id: 'user_admin_01',
    email: 'hamide67@gmail.com',
    full_name: 'مدیر سامانه بحران (حمیده)',
    phone: '09120000000',
    password: 'Hamed987@',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'user_demo_02',
    email: 'user@tour360.ir',
    full_name: 'امدادگر داوطلب (کاربر آزمایشی)',
    phone: '09123456789',
    password: '123456',
    role: 'user',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
];

export const initialPanoramas: Panorama[] = [
  {
    id: 'pano_01',
    title: 'کوچه تخریب‌شده (فضای اول - بحران شهری)',
    file_url: PUBLIC_PANORAMAS['pano_01'],
    width: 4096,
    height: 2048,
    aspect_ratio: 2,
    file_size_bytes: 8420000,
    storage_path: 'panoramas/stage-1/crisis_street_rubble_360.jpg',
    created_at: '2026-01-10T08:30:00Z',
    updated_at: '2026-01-10T08:30:00Z',
  },
  {
    id: 'pano_02',
    title: 'ساختمان آسیب‌دیده (فضای دوم - امداد و نجات در آوار)',
    file_url: PUBLIC_PANORAMAS['pano_02'],
    width: 4096,
    height: 2048,
    aspect_ratio: 2,
    file_size_bytes: 7890000,
    storage_path: 'panoramas/stage-2/crisis_building_interior_360.jpg',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'pano_03',
    title: 'پناهگاه امن و مرکز فرماندهی (فضای سوم - تثبیت ایمنی)',
    file_url: PUBLIC_PANORAMAS['pano_03'],
    width: 4096,
    height: 2048,
    aspect_ratio: 2,
    file_size_bytes: 9150000,
    storage_path: 'panoramas/stage-3/crisis_shelter_safezone_360.jpg',
    created_at: '2026-01-10T09:30:00Z',
    updated_at: '2026-01-10T09:30:00Z',
  },
];

export const initialStages: Stage[] = [
  {
    id: 'stage_01',
    title: 'بخش اول: کوچه تخریب‌شده',
    description: 'بررسی خطرات محیطی، شناسایی نشت گاز و کابل‌های برق، ارزیابی اولیه خودروهای واژگون و مسیر ورود به ساختمان',
    order: 1,
    panorama_id: 'pano_01',
    is_active: true,
    initial_yaw: 0,
    initial_pitch: -5,
    initial_fov: 75,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'stage_02',
    title: 'بخش دوم: ساختمان آسیب‌دیده',
    description: 'ورود به ساختمان نیمه‌ویران، ارزیابی ترک‌های برشی و سازه‌ای، جست‌وجوی محبوسین احتمالی و کنترل راه‌های خروج اضطراری',
    order: 2,
    panorama_id: 'pano_02',
    is_active: true,
    initial_yaw: 30,
    initial_pitch: 0,
    initial_fov: 75,
    created_at: '2026-01-10T10:15:00Z',
    updated_at: '2026-01-10T10:15:00Z',
  },
  {
    id: 'stage_03',
    title: 'بخش سوم: پناهگاه امن مدیریت بحران',
    description: 'تثبیت شرایط آسیب‌دیدگان، ارتباط رادیویی بیسیم با ستاد مرکزی، مدیریت اقلام امدادی و طرح‌ریزی اسکان موقت',
    order: 3,
    panorama_id: 'pano_03',
    is_active: true,
    initial_yaw: -20,
    initial_pitch: -5,
    initial_fov: 75,
    created_at: '2026-01-10T10:30:00Z',
    updated_at: '2026-01-10T10:30:00Z',
  },
];

// 3D coordinates on a sphere of radius ~450
export const initialHotspots: Hotspot[] = [
  // --- Stage 1: Damaged Urban Street (5 Questions + 2 Info points) ---
  {
    id: 'hotspot_s1_q1',
    panorama_id: 'pano_01',
    stage_id: 'stage_01',
    hotspot_type: 'question',
    title: 'سؤال ۱: خطوط و علمک گاز شهری',
    description: 'بررسی ایمنی لوله‌کشی و خطر اشتعال یا انفجار',
    pos_x: -280,
    pos_y: 60,
    pos_z: -340,
    is_active: true,
    order: 1,
    created_at: '2026-01-10T11:00:00Z',
    updated_at: '2026-01-10T11:00:00Z',
  },
  {
    id: 'hotspot_s1_q2',
    panorama_id: 'pano_01',
    stage_id: 'stage_01',
    hotspot_type: 'question',
    title: 'سؤال ۲: کابل‌های افتاده برق فشار قوی',
    description: 'ارزیابی خطر برق‌گرفتگی در معبر دارای آوار',
    pos_x: 180,
    pos_y: 270,
    pos_z: -310,
    is_active: true,
    order: 2,
    created_at: '2026-01-10T11:05:00Z',
    updated_at: '2026-01-10T11:05:00Z',
  },
  {
    id: 'hotspot_s1_q3',
    panorama_id: 'pano_01',
    stage_id: 'stage_01',
    hotspot_type: 'question',
    title: 'سؤال ۳: خودروی آسیب‌دیده و نشت بنزین',
    description: 'اولویت‌بندی امداد به سرنشین در مجاورت مواد سوختنی',
    pos_x: 350,
    pos_y: -140,
    pos_z: -240,
    is_active: true,
    order: 3,
    created_at: '2026-01-10T11:10:00Z',
    updated_at: '2026-01-10T11:10:00Z',
  },
  {
    id: 'hotspot_s1_q4',
    panorama_id: 'pano_01',
    stage_id: 'stage_01',
    hotspot_type: 'question',
    title: 'سؤال ۴: آوار فروریخته و ارزیابی پس‌لرزه',
    description: 'انتخاب معبر امن جهت حرکت به سمت ورودی ساختمان',
    pos_x: -80,
    pos_y: -290,
    pos_z: -330,
    is_active: true,
    order: 4,
    created_at: '2026-01-10T11:15:00Z',
    updated_at: '2026-01-10T11:15:00Z',
  },
  {
    id: 'hotspot_s1_q5',
    panorama_id: 'pano_01',
    stage_id: 'stage_01',
    hotspot_type: 'question',
    title: 'سؤال ۵: نوار خطر و محدوده ورود تیم امداد',
    description: 'قوانین ورود به پهنه قرمز عملیاتی بحران',
    pos_x: -360,
    pos_y: -40,
    pos_z: 250,
    is_active: true,
    order: 5,
    created_at: '2026-01-10T11:20:00Z',
    updated_at: '2026-01-10T11:20:00Z',
  },
  {
    id: 'hotspot_s1_info1',
    panorama_id: 'pano_01',
    stage_id: 'stage_01',
    hotspot_type: 'information',
    title: 'پروتکل ایمنی در معابر دارای آوار',
    description: 'در ثانیه‌های نخست پس از زلزله، به هیچ وجه زیر تیرهای چراغ برق، بالکن‌های معلق و دیوارهای ترک‌خورده توقف نکنید. تا قطع جریان گاز و برق شهری، از روشن کردن هرگونه کبریت، فندک یا حتی کلید برق خودداری نمایید.',
    pos_x: 290,
    pos_y: 120,
    pos_z: 320,
    is_active: true,
    order: 6,
    created_at: '2026-01-10T11:25:00Z',
    updated_at: '2026-01-10T11:25:00Z',
  },
  {
    id: 'hotspot_s1_info2',
    panorama_id: 'pano_01',
    stage_id: 'stage_01',
    hotspot_type: 'information',
    title: 'تجهیزات حفاظت فردی امدادگر (PPE)',
    description: 'کلاه‌خود ایمنی استاندارد، عینک محافظ در برابر ریزگرد، دستکش ضخیم ضدبرش، پوتین‌های کف‌فلزی و ماسک تنفسی فیلتردار پیش‌نیاز هرگونه اقدام جست‌وجو در آوار است.',
    pos_x: 10,
    pos_y: 350,
    pos_z: 270,
    is_active: true,
    order: 7,
    created_at: '2026-01-10T11:30:00Z',
    updated_at: '2026-01-10T11:30:00Z',
  },

  // --- Stage 2: Damaged Building Interior (5 Questions + 2 Info points) ---
  {
    id: 'hotspot_s2_q1',
    panorama_id: 'pano_02',
    stage_id: 'stage_02',
    hotspot_type: 'question',
    title: 'سؤال ۱: ترک‌های قطری برشی دیوار باربر',
    description: 'تشخیص خطر ریزش ناگهانی سقف و دیوار باربر',
    pos_x: -330,
    pos_y: 150,
    pos_z: -270,
    is_active: true,
    order: 1,
    created_at: '2026-01-10T12:00:00Z',
    updated_at: '2026-01-10T12:00:00Z',
  },
  {
    id: 'hotspot_s2_q2',
    panorama_id: 'pano_02',
    stage_id: 'stage_02',
    hotspot_type: 'question',
    title: 'سؤال ۲: راه‌پله و سقف مسدودشده',
    description: 'استفاده یا عدم استفاده از راه‌پله در زمان پس‌لرزه',
    pos_x: 60,
    pos_y: 310,
    pos_z: -300,
    is_active: true,
    order: 2,
    created_at: '2026-01-10T12:05:00Z',
    updated_at: '2026-01-10T12:05:00Z',
  },
  {
    id: 'hotspot_s2_q3',
    panorama_id: 'pano_02',
    stage_id: 'stage_02',
    hotspot_type: 'question',
    title: 'سؤال ۳: مثلث حیات و نقاط امن پناه‌گیری',
    description: 'شناسایی مناسب‌ترین نقطه پناه برای محبوسین داخل اتاق',
    pos_x: 340,
    pos_y: -120,
    pos_z: -260,
    is_active: true,
    order: 3,
    created_at: '2026-01-10T12:10:00Z',
    updated_at: '2026-01-10T12:10:00Z',
  },
  {
    id: 'hotspot_s2_q4',
    panorama_id: 'pano_02',
    stage_id: 'stage_02',
    hotspot_type: 'question',
    title: 'سؤال ۴: پنجره شکسته و سقوط خرده‌شیشه‌ها',
    description: 'ایمن‌سازی معبر خروج و پرهیز از بریدگی شریانی',
    pos_x: -370,
    pos_y: -70,
    pos_z: 210,
    is_active: true,
    order: 4,
    created_at: '2026-01-10T12:15:00Z',
    updated_at: '2026-01-10T12:15:00Z',
  },
  {
    id: 'hotspot_s2_q5',
    panorama_id: 'pano_02',
    stage_id: 'stage_02',
    hotspot_type: 'question',
    title: 'سؤال ۵: علامت‌گذاری ساختمان (نشان INSARAG)',
    description: 'کدگذاری بین‌المللی جست‌وجوی افراد زنده و کشته‌شدگان',
    pos_x: 170,
    pos_y: 80,
    pos_z: 390,
    is_active: true,
    order: 5,
    created_at: '2026-01-10T12:20:00Z',
    updated_at: '2026-01-10T12:20:00Z',
  },
  {
    id: 'hotspot_s2_info1',
    panorama_id: 'pano_02',
    stage_id: 'stage_02',
    hotspot_type: 'information',
    title: 'نشانه‌گذاری استاندارد بین‌المللی جست‌وجو (INSARAG)',
    description: 'رسم علامت ضربدر (X) روی ورودی ساختمان: در سمت چپ تاریخ و ساعت ورود تیم، در بالا شناسه تیم امدادی، در سمت راست خطرات شناسایی‌شده (مانند نشت گاز) و در پایین تعداد نجات‌یافتگان زنده و متوفیان درج می‌شود.',
    pos_x: 290,
    pos_y: -190,
    pos_z: 280,
    is_active: true,
    order: 6,
    created_at: '2026-01-10T12:25:00Z',
    updated_at: '2026-01-10T12:25:00Z',
  },
  {
    id: 'hotspot_s2_info2',
    panorama_id: 'pano_02',
    stage_id: 'stage_02',
    hotspot_type: 'information',
    title: 'خفگی ناشی از ریزگردهای ساختمانی',
    description: 'استنشاق غبار ناشی از ریزش بتن و گچ می‌تواند در کمتر از چند دقیقه باعث اسپاسم ریوی شود. در صورت نبود ماسک، استفاده از پارچه نمدار روی دهان و بینی الزامی است.',
    pos_x: -210,
    pos_y: 280,
    pos_z: 270,
    is_active: true,
    order: 7,
    created_at: '2026-01-10T12:30:00Z',
    updated_at: '2026-01-10T12:30:00Z',
  },

  // --- Stage 3: Safe Shelter & Crisis Command (5 Questions + 2 Info points) ---
  {
    id: 'hotspot_s3_q1',
    panorama_id: 'pano_03',
    stage_id: 'stage_03',
    hotspot_type: 'question',
    title: 'سؤال ۱: تریاژ اولیه مصدومان (START Triage)',
    description: 'اولویت‌بندی درمان بر اساس رنگ‌های استاندارد بحران',
    pos_x: -290,
    pos_y: -110,
    pos_z: -320,
    is_active: true,
    order: 1,
    created_at: '2026-01-10T13:00:00Z',
    updated_at: '2026-01-10T13:00:00Z',
  },
  {
    id: 'hotspot_s3_q2',
    panorama_id: 'pano_03',
    stage_id: 'stage_03',
    hotspot_type: 'question',
    title: 'سؤال ۲: جعبه کمک‌های اولیه و کنترل خونریزی شریانی',
    description: 'کاربرد صحیح تورنیکه (رگ‌بند) در تروماهای شدید',
    pos_x: 210,
    pos_y: -160,
    pos_z: -360,
    is_active: true,
    order: 2,
    created_at: '2026-01-10T13:05:00Z',
    updated_at: '2026-01-10T13:05:00Z',
  },
  {
    id: 'hotspot_s3_q3',
    panorama_id: 'pano_03',
    stage_id: 'stage_03',
    hotspot_type: 'question',
    title: 'سؤال ۳: بیسیم و ارتباطات اضطراری (VHF/HF)',
    description: 'پروتکل ارسال پیام اضطراری در شرایط قطعی اینترنت و موبایل',
    pos_x: 340,
    pos_y: 120,
    pos_z: -270,
    is_active: true,
    order: 3,
    created_at: '2026-01-10T13:10:00Z',
    updated_at: '2026-01-10T13:10:00Z',
  },
  {
    id: 'hotspot_s3_q4',
    panorama_id: 'pano_03',
    stage_id: 'stage_03',
    hotspot_type: 'question',
    title: 'سؤال ۴: مدیریت بهداشت و آب آشامیدنی پناهگاه',
    description: 'روش‌های گندزدایی آب آشامیدنی در ساعات اولیه اسکان',
    pos_x: -360,
    pos_y: 130,
    pos_z: 220,
    is_active: true,
    order: 4,
    created_at: '2026-01-10T13:15:00Z',
    updated_at: '2026-01-10T13:15:00Z',
  },
  {
    id: 'hotspot_s3_q5',
    panorama_id: 'pano_03',
    stage_id: 'stage_03',
    hotspot_type: 'question',
    title: 'سؤال ۵: نقشه عملیاتی و تخلیه ثانویه',
    description: 'تعیین کریدورهای هوایی و زمینی برای اعزام مصدومان بدحال',
    pos_x: 40,
    pos_y: 360,
    pos_z: -260,
    is_active: true,
    order: 5,
    created_at: '2026-01-10T13:20:00Z',
    updated_at: '2026-01-10T13:20:00Z',
  },
  {
    id: 'hotspot_s3_info1',
    panorama_id: 'pano_03',
    stage_id: 'stage_03',
    hotspot_type: 'information',
    title: 'کدگذاری تریاژ START (ساده و سریع)',
    description: 'قرمز: فوری (نیاز به مداخله حیاتی زیر ۲ ساعت) | زرد: تاخیری (مصدوم جدی اما تنفس و هوشیاری پایدار) | سبز: سرپایی (افرادی که توان راه رفتن دارند) | سیاه: متوفی یا جراحات غیرقابل احیا.',
    pos_x: -160,
    pos_y: 260,
    pos_z: 320,
    is_active: true,
    order: 6,
    created_at: '2026-01-10T13:25:00Z',
    updated_at: '2026-01-10T13:25:00Z',
  },
  {
    id: 'hotspot_s3_info2',
    panorama_id: 'pano_03',
    stage_id: 'stage_03',
    hotspot_type: 'information',
    title: 'حمایت روانی پس از سانحه (PFA)',
    description: 'در ساعات بحران، گوش دادن فعال، ارائه اطلاعات شفاف و پرهیز از شایعه‌سازی، اضطراب جمعی پناهگاه را مهار کرده و از شوک روانی بازماندگان جلوگیری می‌کند.',
    pos_x: 280,
    pos_y: -180,
    pos_z: 300,
    is_active: true,
    order: 7,
    created_at: '2026-01-10T13:30:00Z',
    updated_at: '2026-01-10T13:30:00Z',
  },
];

export const initialQuestions: Question[] = [
  // --- Stage 1 Questions (Damaged Street) ---
  {
    id: 'q_s1_1',
    stage_id: 'stage_01',
    hotspot_id: 'hotspot_s1_q1',
    question_text: 'در صورت استشمام بوی شدید گاز یا مشاهده شکستگی علمک در معبر زلزله‌زده، نخستین اقدام نجات‌بخش چیست؟',
    explanation: 'دور شدن سریع خلاف جهت وزش باد، هشدار کلامی به اطرافیان، پرهیز مطلق از زدن کلیدهای برق یا تماس موبایل و اطلاع به تیم امداد در فاصله امن الزامی است.',
    order: 1,
    is_active: true,
    created_at: '2026-01-10T14:00:00Z',
    updated_at: '2026-01-10T14:00:00Z',
  },
  {
    id: 'q_s1_2',
    stage_id: 'stage_01',
    hotspot_id: 'hotspot_s1_q2',
    question_text: 'هنگام برخورد با کابل‌های آویزان یا افتاده برق در کف کوچه، رعایت چه فاصله‌ای از نقطه اتصال به زمین ضروری است؟',
    explanation: 'بر اساس پروتکل‌های ایمنی برق، به دلیل ایجاد ولتاژ گامی (Step Voltage) در زمین‌های مرطوب یا بتنی، باید حداقل شعاع ۸ تا ۱۰ متری رعایت شود و با گام‌های چسبیده و بدون پرش عقب‌نشینی کرد.',
    order: 2,
    is_active: true,
    created_at: '2026-01-10T14:05:00Z',
    updated_at: '2026-01-10T14:05:00Z',
  },
  {
    id: 'q_s1_3',
    stage_id: 'stage_01',
    hotspot_id: 'hotspot_s1_q3',
    question_text: 'خودرویی در اثر آوار واژگون شده و بوی بنزین به مشام می‌رسد. سرنشین هوشیار اما محبوس است؛ اولویت چیست؟',
    explanation: 'تثبیت خودرو برای ممانعت از لغزش، خاموش کردن سوئیچ در صورت دسترسی بدون ایجاد جرقه، آماده‌سازی کپسول پودر و گاز و عدم جابجایی غیراصولی گردن مصدوم تا رسیدن ابزار برش هیدرولیک.',
    order: 3,
    is_active: true,
    created_at: '2026-01-10T14:10:00Z',
    updated_at: '2026-01-10T14:10:00Z',
  },
  {
    id: 'q_s1_4',
    stage_id: 'stage_01',
    hotspot_id: 'hotspot_s1_q4',
    question_text: 'کدام مسیر برای عبور پیاده امدادگر به سمت ورودی ساختمان در یک کوچه آوارگرفته کم‌خطرتر است؟',
    explanation: 'مرکز معبر به دور از پای دیوارهای ناپایدار و بالکن‌های نیمه‌معلق، با بررسی پایداری جای پا روی آوارهای سخت.',
    order: 4,
    is_active: true,
    created_at: '2026-01-10T14:15:00Z',
    updated_at: '2026-01-10T14:15:00Z',
  },
  {
    id: 'q_s1_5',
    stage_id: 'stage_01',
    hotspot_id: 'hotspot_s1_q5',
    question_text: 'نوار قرمز خطر و حصارکشی امدادی در ابتدای کوچه چه معنایی برای تیم‌های عملیاتی دارد؟',
    explanation: 'پهنه قرمز نشانگر خطر قریب‌الوقوع ریزش ثانویه یا نشت مواد سمی است و ورود به آن صرفاً با مجوز ارزیاب ارشد سازه مجاز است.',
    order: 5,
    is_active: true,
    created_at: '2026-01-10T14:20:00Z',
    updated_at: '2026-01-10T14:20:00Z',
  },

  // --- Stage 2 Questions (Damaged Building Interior) ---
  {
    id: 'q_s2_1',
    stage_id: 'stage_02',
    hotspot_id: 'hotspot_s2_q1',
    question_text: 'مشاهده ترک‌های عمیق ضربدری به شکل حرف X روی دیوارهای باربر بتنی نشانگر چیست؟',
    explanation: 'ترک‌های برشی ضربدری (Shear Cracks) نشانه عبور سازه از آستانه پایداری جانبی و خطر آنی فروریزش در پس‌لرزه بعدی است.',
    order: 1,
    is_active: true,
    created_at: '2026-01-10T15:00:00Z',
    updated_at: '2026-01-10T15:00:00Z',
  },
  {
    id: 'q_s2_2',
    stage_id: 'stage_02',
    hotspot_id: 'hotspot_s2_q2',
    question_text: 'چرا استفاده از باکس راه‌پله در ساختمان‌های با خسارت متوسط تا شدید پس از زلزله بسیار پرریسک است؟',
    explanation: 'راه‌پله‌ها به دلیل صلبیت بالا زودتر از تیرها و ستون‌ها در اتصالات دچار جداشدگی بتن و گسست میلگرد می‌شوند.',
    order: 2,
    is_active: true,
    created_at: '2026-01-10T15:05:00Z',
    updated_at: '2026-01-10T15:05:00Z',
  },
  {
    id: 'q_s2_3',
    stage_id: 'stage_02',
    hotspot_id: 'hotspot_s2_q3',
    question_text: 'در صورت وقوع پس‌لرزه ناگهانی در حین حضور در این اتاق ویران، اصولی‌ترین اقدام پناه‌گیری چیست؟',
    explanation: 'تکنیک بشین، پناه بگیر و محکم بچسب (Drop, Cover, Hold On) در کنار یک جسم حجیم و مقاوم به عنوان ضربه‌گیر آوار.',
    order: 3,
    is_active: true,
    created_at: '2026-01-10T15:10:00Z',
    updated_at: '2026-01-10T15:10:00Z',
  },
  {
    id: 'q_s2_4',
    stage_id: 'stage_02',
    hotspot_id: 'hotspot_s2_q4',
    question_text: 'برای نجات فرد محبوسی که زیر کمد سنگین افتاده اما اندام‌هایش فشرده شده است، چه ریسکی باید ارزیابی شود؟',
    explanation: 'سندروم له‌شدگی (Crush Syndrome)؛ رهاسازی ناگهانی پس از بیش از ۲۰ دقیقه فشار ممکن است سموم میوگلوبین را به کلیه روانه کند.',
    order: 4,
    is_active: true,
    created_at: '2026-01-10T15:15:00Z',
    updated_at: '2026-01-10T15:15:00Z',
  },
  {
    id: 'q_s2_5',
    stage_id: 'stage_02',
    hotspot_id: 'hotspot_s2_q5',
    question_text: 'در علامت‌گذاری ضربدر INSARAG روی دیوار بیرونی اتاق، عدد درج‌شده در ربع پایینی به چه معناست؟',
    explanation: 'ربع پایینی نشانگر تعداد افراد نجات‌یافته زنده (L) و تعداد افراد متوفی (D) یافت‌شده در آن واحد است.',
    order: 5,
    is_active: true,
    created_at: '2026-01-10T15:20:00Z',
    updated_at: '2026-01-10T15:20:00Z',
  },

  // --- Stage 3 Questions (Safe Shelter & Crisis Operations) ---
  {
    id: 'q_s3_1',
    stage_id: 'stage_03',
    hotspot_id: 'hotspot_s3_q1',
    question_text: 'در سیستم تریاژ START، مصدومی با نرخ تنفس ۳۲ در دقیقه و عدم توانایی در اجرای دستور ساده چه برچسبی می‌گیرد؟',
    explanation: 'برچسب قرمز (فوری)؛ تنفس بالاتر از ۳۰ بار در دقیقه یا اختلال وضعیت هوشیاری، مصدوم را بلافاصله در اولویت یک درمان قرار می‌دهد.',
    order: 1,
    is_active: true,
    created_at: '2026-01-10T16:00:00Z',
    updated_at: '2026-01-10T16:00:00Z',
  },
  {
    id: 'q_s3_2',
    stage_id: 'stage_03',
    hotspot_id: 'hotspot_s3_q2',
    question_text: 'هنگام بستن تورنیکه (رگ‌بند) برای قطع خونریزی کشنده شریانی اندام، ثبت چه موردی روی پیشانی یا برچسب مصدوم حیاتی است؟',
    explanation: 'ساعت و دقیقه دقیق بستن تورنیکه (مثلاً TK 14:25) تا پزشک در اتاق عمل بتواند از مرگ بافت اندام ممانعت نماید.',
    order: 2,
    is_active: true,
    created_at: '2026-01-10T16:05:00Z',
    updated_at: '2026-01-10T16:05:00Z',
  },
  {
    id: 'q_s3_3',
    stage_id: 'stage_03',
    hotspot_id: 'hotspot_s3_q3',
    question_text: 'در ارتباط با بیسیم اضطراری با مرکز دیسپاچ بحران، رعایت کدام اصل مخابراتی ضروری است؟',
    explanation: 'اصل اختصار، شفافیت، اعلام موقعیت جغرافیایی دقیق و عدم اشغال بیهوده کانال اصلی امداد.',
    order: 3,
    is_active: true,
    created_at: '2026-01-10T16:10:00Z',
    updated_at: '2026-01-10T16:10:00Z',
  },
  {
    id: 'q_s3_4',
    stage_id: 'stage_03',
    hotspot_id: 'hotspot_s3_q4',
    question_text: 'حداقل نیاز آبی استاندارد اسفیر (Sphere Project) برای هر فرد در پناهگاه اضطراری روزانه چقدر است؟',
    explanation: 'حداقل ۱۵ لیتر برای هر فرد در روز شامل شرب، بهداشت فردی و پخت‌وپز اولیه.',
    order: 4,
    is_active: true,
    created_at: '2026-01-10T16:15:00Z',
    updated_at: '2026-01-10T16:15:00Z',
  },
  {
    id: 'q_s3_5',
    stage_id: 'stage_03',
    hotspot_id: 'hotspot_s3_q5',
    question_text: 'در نقشه مدیریت بحران، اولویت اسکان موقت آسیب‌دیدگان نباید در مجاورت کدام یک از موارد زیر باشد؟',
    explanation: 'پرهیز از حریم پمپ‌بنزین‌ها، خطوط گاز فشار قوی، دکل‌های برق، شیب‌های مستعد زمین‌لغزش و بستر مسیل‌های سیلابی.',
    order: 5,
    is_active: true,
    created_at: '2026-01-10T16:20:00Z',
    updated_at: '2026-01-10T16:20:00Z',
  },
];

export const initialQuestionOptions: QuestionOption[] = [
  // --- Stage 1 Options ---
  // Q1
  { id: 'opt_s1_q1_1', question_id: 'q_s1_1', option_text: 'خروج فوری به خلاف جهت باد و اعلام خطر بدون استفاده از لوازم جرقه زن', is_correct: true, order: 1 },
  { id: 'opt_s1_q1_2', question_id: 'q_s1_1', option_text: 'روشن کردن فندک برای یافتن دقیق محل نشت گاز', is_correct: false, order: 2 },
  { id: 'opt_s1_q1_3', question_id: 'q_s1_1', option_text: 'بستن دستمال خیس دور علمک بدون هشدار به دیگران', is_correct: false, order: 3 },
  { id: 'opt_s1_q1_4', question_id: 'q_s1_1', option_text: 'تماس تلفنی با موبایل دقیقاً در کنار لوله نشت‌کننده', is_correct: false, order: 4 },

  // Q2
  { id: 'opt_s1_q2_1', question_id: 'q_s1_2', option_text: 'رعایت حداقل فاصله ۸ تا ۱۰ متری و دور شدن با گام‌های به هم چسبیده', is_correct: true, order: 1 },
  { id: 'opt_s1_q2_2', question_id: 'q_s1_2', option_text: 'پریدن با گام‌های بلند از روی کابل برق', is_correct: false, order: 2 },
  { id: 'opt_s1_q2_3', question_id: 'q_s1_3', option_text: 'جابجایی کابل با یک تکه چوب نم‌دار یا میله آهنی', is_correct: false, order: 3 },
  { id: 'opt_s1_q2_4', question_id: 'q_s1_4', option_text: 'آب پاشیدن روی کابل برای خنک شدن سیم', is_correct: false, order: 4 },

  // Q3
  { id: 'opt_s1_q3_1', question_id: 'q_s1_3', option_text: 'تثبیت خودرو، رفع خطر حریق و پرهیز از حرکت دادن ستون فقرات مصدوم', is_correct: true, order: 1 },
  { id: 'opt_s1_q3_2', question_id: 'q_s1_3', option_text: 'کشیدن سریع دست و پای مصدوم از شیشه شکسته به بیرون', is_correct: false, order: 2 },
  { id: 'opt_s1_q3_3', question_id: 'q_s1_3', option_text: 'روشن کردن موتور خودرو برای خلاص کردن دنده', is_correct: false, order: 3 },
  { id: 'opt_s1_q3_4', question_id: 'q_s1_3', option_text: 'غلتاندن مجدد خودرو به حالت اولیه توسط امدادگران عادی', is_correct: false, order: 4 },

  // Q4
  { id: 'opt_s1_q4_1', question_id: 'q_s1_4', option_text: 'حرکت از مرکز معبر با فاصله از دیوارهای ناپایدار و بالکن‌های معلق', is_correct: true, order: 1 },
  { id: 'opt_s1_q4_2', question_id: 'q_s1_4', option_text: 'دویدن چسبیده به پای دیوارهای ترک‌خورده بلند', is_correct: false, order: 2 },
  { id: 'opt_s1_q4_3', question_id: 'q_s1_4', option_text: 'حرکت از زیر سازه‌های فلزی آویزان سست', is_correct: false, order: 3 },
  { id: 'opt_s1_q4_4', question_id: 'q_s1_4', option_text: 'بالا رفتن از تپه‌های آوار ناپایدار بدون عصای ارزیابی', is_correct: false, order: 4 },

  // Q5
  { id: 'opt_s1_q5_1', question_id: 'q_s1_5', option_text: 'محدوده با خطر بالای ریزش مجدد و لزوم مجوز تخصصی سازه', is_correct: true, order: 1 },
  { id: 'opt_s1_q5_2', question_id: 'q_s1_5', option_text: 'محل پارک خودروهای شخصی اهالی محل', is_correct: false, order: 2 },
  { id: 'opt_s1_q5_3', question_id: 'q_s1_5', option_text: 'محل توزیع رایگان مواد غذایی و چای', is_correct: false, order: 3 },
  { id: 'opt_s1_q5_4', question_id: 'q_s1_5', option_text: 'مسیر باز و بدون هرگونه ریسک آوار', is_correct: false, order: 4 },

  // --- Stage 2 Options ---
  // Q1
  { id: 'opt_s2_q1_1', question_id: 'q_s2_1', option_text: 'ترک‌های برشی خطرناک و احتمال بالای فروریزش ناگهانی با پس‌لرزه', is_correct: true, order: 1 },
  { id: 'opt_s2_q1_2', question_id: 'q_s2_1', option_text: 'ترک‌های سطحی رنگ دیوار بدون هیچ اهمیت سازه‌ای', is_correct: false, order: 2 },
  { id: 'opt_s2_q1_3', question_id: 'q_s2_1', option_text: 'نشانه نشست تدریجی خاک در درازمدت ۵۰ ساله', is_correct: false, order: 3 },
  { id: 'opt_s2_q1_4', question_id: 'q_s2_1', option_text: 'علامت رطوبت باران در گچ دیوار', is_correct: false, order: 4 },

  // Q2
  { id: 'opt_s2_q2_1', question_id: 'q_s2_1', option_text: 'صلبیت بالا و آسیب‌پذیری شدید اتصالات راه‌پله در برابر پس‌لرزه', is_correct: true, order: 1 },
  { id: 'opt_s2_q2_2', question_id: 'q_s2_2', option_text: 'تاریک بودن فضای راه‌پله‌ها در شب', is_correct: false, order: 2 },
  { id: 'opt_s2_q2_3', question_id: 'q_s2_3', option_text: 'خستگی پاهای امدادگران در بالا رفتن از پله', is_correct: false, order: 3 },
  { id: 'opt_s2_q2_4', question_id: 'q_s2_4', option_text: 'خراب شدن کف‌پوش سرامیکی پله‌ها', is_correct: false, order: 4 },

  // Q3
  { id: 'opt_s2_q3_1', question_id: 'q_s2_3', option_text: 'نشستن و پناه گرفتن در کنار سازه حجیم مقاوم و محافظت از سر', is_correct: true, order: 1 },
  { id: 'opt_s2_q3_2', question_id: 'q_s2_3', option_text: 'ایستادن زیر چارچوب درهای آسیب‌دیده و کج‌شده', is_correct: false, order: 2 },
  { id: 'opt_s2_q3_3', question_id: 'q_s2_3', option_text: 'دویدن به سمت بالکن و پریدن به کوچه', is_correct: false, order: 3 },
  { id: 'opt_s2_q3_4', question_id: 'q_s2_3', option_text: 'دراز کشیدن صاف در وسط اتاق زیر لوستر سقف', is_correct: false, order: 4 },

  // Q4
  { id: 'opt_s2_q4_1', question_id: 'q_s2_4', option_text: 'سندروم له‌شدگی و لزوم سرم‌تراپی همزمان قبل از آزادسازی آوار', is_correct: true, order: 1 },
  { id: 'opt_s2_q4_2', question_id: 'q_s2_4', option_text: 'سرماخوردگی مصدوم به دلیل وزش باد', is_correct: false, order: 2 },
  { id: 'opt_s2_q4_3', question_id: 'q_s2_3', option_text: 'کثیف شدن لباس‌های امدادگر با گردوخاک', is_correct: false, order: 3 },
  { id: 'opt_s2_q4_4', question_id: 'q_s2_4', option_text: 'شکستن پایه کمد در هنگام کشیدن', is_correct: false, order: 4 },

  // Q5
  { id: 'opt_s2_q5_1', question_id: 'q_s2_5', option_text: 'تعداد نجات‌یافتگان زنده (L) و متوفیان خارج‌شده (D)', is_correct: true, order: 1 },
  { id: 'opt_s2_q5_2', question_id: 'q_s2_5', option_text: 'شماره تلفن صاحب ساختمان', is_correct: false, order: 2 },
  { id: 'opt_s2_q5_3', question_id: 'q_s2_3', option_text: 'متراژ دقیق زیربنای ساختمان', is_correct: false, order: 3 },
  { id: 'opt_s2_q5_4', question_id: 'q_s2_4', option_text: 'قیمت هر متر مربع ملک مسکونی', is_correct: false, order: 4 },

  // --- Stage 3 Options ---
  // Q1
  { id: 'opt_s3_q1_1', question_id: 'q_s3_1', option_text: 'قرمز (فوری و اولویت اول مداخله)', is_correct: true, order: 1 },
  { id: 'opt_s3_q1_2', question_id: 'q_s3_2', option_text: 'سبز (سرپایی و بدون نیاز به انتقال فوری)', is_correct: false, order: 2 },
  { id: 'opt_s3_q1_3', question_id: 'q_s3_3', option_text: 'زرد (تاخیری با تنفس طبیعی)', is_correct: false, order: 3 },
  { id: 'opt_s3_q1_4', question_id: 'q_s3_4', option_text: 'سفید (ترخیص کامل)', is_correct: false, order: 4 },

  // Q2
  { id: 'opt_s3_q2_1', question_id: 'q_s3_2', option_text: 'زمان دقیق بستن تورنیکه بر حسب ساعت و دقیقه', is_correct: true, order: 1 },
  { id: 'opt_s3_q2_2', question_id: 'q_s3_2', option_text: 'کد ملی بستگان درجه اول مصدوم', is_correct: false, order: 2 },
  { id: 'opt_s3_q2_3', question_id: 'q_s3_3', option_text: 'وزن تقریبی لباس‌های مصدوم', is_correct: false, order: 3 },
  { id: 'opt_s3_q2_4', question_id: 'q_s3_4', option_text: 'نام شرکت سازنده تورنیکه', is_correct: false, order: 4 },

  // Q3
  { id: 'opt_s3_q3_1', question_id: 'q_s3_3', option_text: 'رعایت اختصار، اعلام موقعیت دقیق و خالی نگه داشتن کانال اضطراری', is_correct: true, order: 1 },
  { id: 'opt_s3_q3_2', question_id: 'q_s3_2', option_text: 'مکالمه طولانی درباره شرح احساسات شخصی امدادگر', is_correct: false, order: 2 },
  { id: 'opt_s3_q3_3', question_id: 'q_s3_3', option_text: 'پخش موسیقی روی فرکانس نجات برای آرامش افراد', is_correct: false, order: 3 },
  { id: 'opt_s3_q3_4', question_id: 'q_s3_4', option_text: 'استفاده از اصطلاحات نامفهوم غیررسمی', is_correct: false, order: 4 },

  // Q4
  { id: 'opt_s3_q4_1', question_id: 'q_s3_4', option_text: 'حداقل ۱۵ لیتر برای هر نفر در شبانه‌روز (بر اساس استاندارد بین‌المللی اسفیر)', is_correct: true, order: 1 },
  { id: 'opt_s3_q4_2', question_id: 'q_s3_2', option_text: 'تنها نیم لیتر در هفته برای کل پناهگاه', is_correct: false, order: 2 },
  { id: 'opt_s3_q4_3', question_id: 'q_s3_3', option_text: 'بیش از ۲۰۰ لیتر در هر ساعت برای هر فرد', is_correct: false, order: 3 },
  { id: 'opt_s3_q4_4', question_id: 'q_s3_4', option_text: 'نیاز به آب وجود ندارد و آبمیوه صنعتی کفایت می‌کند', is_correct: false, order: 4 },

  // Q5
  { id: 'opt_s3_q5_1', question_id: 'q_s3_5', option_text: 'دوری از پمپ‌بنزین‌ها، کابل‌های فشار قوی، دامنه‌های لغزشی و مسیل‌ها', is_correct: true, order: 1 },
  { id: 'opt_s3_q5_2', question_id: 'q_s3_2', option_text: 'دقیقاً در کف دره‌های سیلابی برای دسترسی به آب باران', is_correct: false, order: 2 },
  { id: 'opt_s3_q5_3', question_id: 'q_s3_3', option_text: 'زیر دکل‌های بزرگ مخابراتی فلزی بدون مهار', is_correct: false, order: 3 },
  { id: 'opt_s3_q5_4', question_id: 'q_s3_4', option_text: 'چسبیده به انبارهای نگهداری گاز مایع LPG', is_correct: false, order: 4 },
];

export const initialSiteContent: SiteContent[] = [
  {
    id: 'sc_rule',
    key: 'passing_rule',
    title: 'قانون عبور از فضاهای تور بحران',
    content: 'در هر محیط ۳۶۰ درجه ۵ موقعیت کلیدی ارزیابی تعبیه شده است. کاربر باید به هر ۵ سؤال پاسخ صحیح بدهد (۵ از ۵) تا سناریو به صورت خودکار و پیوسته مسیر ورود به فضای ۳۶۰ بعدی را بازگشایی کند.',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'sc_guide',
    key: 'viewer_guide',
    title: 'داستان و پیمایش تور مجازی مدیریت بحران',
    content: 'شما به عنوان امدادگر وارد یک بحران شهری زلزله شده‌اید: از کوچه تخریب‌شده آغاز می‌کنید، با تصمیم‌های صحیح وارد ساختمان آسیب‌دیده می‌شوید و در نهایت مصدومان را به پناهگاه امن هدایت می‌نمایید.',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'sc_about',
    key: 'about_platform',
    title: 'درباره تور یکپارچه مدیریت بحران',
    content: 'این شبیه‌ساز ۳۶۰ درجه داستان‌محور با Three.js محیط‌های واقعی مدیریت بحران شهری در ایران را مدل‌سازی کرده و آموزش واکنش اضطراری را به تجربه‌ای ملموس و پیوسته تبدیل نموده است.',
    updated_at: '2026-01-10T10:00:00Z',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'log_01',
    user_id: 'user_admin_01',
    user_email: 'admin@tour360.ir',
    action: 'login',
    details: 'ورود فرمانده عملیات به سامانه مدیریت بحران',
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'log_02',
    user_id: 'user_admin_01',
    user_email: 'admin@tour360.ir',
    action: 'create_panorama',
    details: 'بارگذاری پانورامای کوچه تخریب‌شده شهری',
    created_at: '2026-01-10T08:30:00Z',
  },
  {
    id: 'log_03',
    user_id: 'user_admin_01',
    user_email: 'admin@tour360.ir',
    action: 'create_hotspot',
    details: 'تعیین نقطه ارزیابی نشت گاز با Three.js Raycasting',
    created_at: '2026-01-10T11:00:00Z',
  },
  {
    id: 'log_04',
    user_id: 'user_demo_02',
    user_email: 'user@tour360.ir',
    action: 'login',
    details: 'ورود امدادگر داوطلب و شروع سناریوی تور بحران',
    created_at: '2026-01-15T10:00:00Z',
  },
];
